name: chat_app_read
description: チャット型SNSで既読機能を実装

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  cloud_firestore: 
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_riverpod:
  go_router:
  uuid:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any


flutter:
  uses-material-design: true

